server {
    listen 443 ssl;
    server_name nube.refacrtb.com.mx;

    ssl_certificate /etc/letsencrypt/live/nube.refacrtb.com.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nube.refacrtb.com.mx/privkey.pem;

    location / {
        proxy_pass http://nextcloud:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
