server {
    listen 443 ssl;
    server_name www.refacrtb.com.mx;

    ssl_certificate /etc/letsencrypt/live/www.refacrtb.com.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.refacrtb.com.mx/privkey.pem;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
